[package]
name = "apyr"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
anyhow = "1.0.75"
better-panic = "0.3.0"
crossterm = "0.27.0"
ratatui = "0.24.0"
regex = "1.10.2"
signal-hook = "0.3.17"
